### ISSUE TITLE
Уезжают колонки редактора если язьіков больше чем 2

### ISSUE THREAD

**Issue by levonet** [EL-shadow/synceditor#23]
В теории больше 4 не должно бьіть пока.
[Пример 3 язьіка](https://sync.yalta.net.ua/synceditor/?branch=s235&path=text%2Fa_puşkin%2F__bağçasaray_çeşmesi̇&filename=a_puşkin__bağçasaray_çeşmesi̇)
[Пример 4 язьіка](https://sync.yalta.net.ua/synceditor/?branch=s242&path=text%2Fernest_heminguey%2F__kilimancaro_qarları%2F_part&filename=ernest_heminguey__kilimancaro_qarları_part_1)

**Comment by EL-shadow** [comment]
Блин, мало того что VPN нужен, так и еще мой акк не дает к закрытой репе доступ.
Заведу новый акк для тестирования, и запрошу доступ.

**Comment by EL-shadow** [comment]
Сейчас в коде, для подсветки синхронизации, захардкожено всегда сравнивать 1 и 2 столбец.
Т.е. для 3-го столбца рисуется цвет который получили на сравнении 1 и 2 ))) 
Я планировал сделать для 2+ языков интерфейс в котором можно выбрать какие 2 языка сейчас хотим видеть. Т.е. всегда показывать только 2 столбца.
Мне кажется что редактирующему пользователю будет сложно сравнивать больше 2х языков.

Ок сделать такое ограничение и добавить возможность выбрать в интерфейсе?

**Comment by EL-shadow** [comment]
В целом на будущее можно сделать возможность отображение больше 2 столбцов, например добавить горизонтальный скролл, а для подсветки пофиксить сравнение: брать при рендеринге 1й (как эталонный) и текущий столбец.

**Comment by levonet** [comment]
> Мне кажется что редактирующему пользователю будет сложно сравнивать больше 2х языков.

как раз наоборот, приводить к еталону все язьіки в один проход намного удобней, чем делать єто по 1 язьіку в много проходов.

По єтому лучше оставить как есть.
Что касается подсветки, то можно делать ее по отношению к еталону.

**Comment by levonet** [comment]
Нужно оставить все язьіки, пока. Их пока не будет более 4-х.
Єто удобно еще по тому, что текст сильно раз'езжается, и синхронизатор постоянно ориентируется на другие язьіки.
Если оставить 2 язьіка, то такая видимость исчезает и в єтом случае каждьій следующий проход синхронизации может приводить к тому, что прийдется заново синхронизировать предидущие файльі.
То-есть оставить видимьіми только 2 язьіка не только не удобно, но и опасно.
