### ISSUE TITLE
Статистика синхронизации

### ISSUE THREAD

**Issue by levonet** [EL-shadow/synceditor#24]
С филологами мьі договариваемся про синхронизацию на платной основе.
Для того чтоб расчитать об'ем используем страницьі обработаного текста.
Нужно в интерфейсе вьівести кол-во страниц, наверно где-то в шапке с точностью до сотьіх.
Страницьі расчитьіваются по формуле:
сумма всех символов (включая спецсимврльі: пробельі, пунктуация) во всех колонках деленая на 1800.

**Comment by EL-shadow** [comment]
Часто длина правого и левого текста не совпадает, какой мы хотим посчитать, самый длинный или вывести по каждому тексту?

**Comment by levonet** [comment]
мьі хотим посчитать сумму всех текстов

**Comment by EL-shadow** [comment]
1. Допустим пользователь открывает 2 текста, и в одном на 10 строк больше, он принимает решение удалить эти 10 строк т.к. для них нет перевода, не с чем синхронизировать. При открытии счетчик показывал Х, после удаления он уменьшается. Это будет ожидаемым поведением?
2. Хотим ли при подсчете схлопывать пробельные последовательности до одного символа?

**Comment by levonet** [comment]
1. Стоимость работьі расчитьівается на основе суммьі вех текстов. По єтому нужно считать все.
2. Єтим можно принебречь.
